---
# tasks file for mrdatamapper.akademiano_youtrack

- name: Install required packages
  become: yes
  apt:
    name: "{{list_youtrack_required_packages}}"
    state: latest
    cache_valid_time: 3600

- systemd:
    name: youtrack
    enabled: yes
    state: stopped
  become: yes
  failed_when: false

- file:
    path: "{{item}}"
    state: directory
    mode: "u=rwX,g=rX,o=-rwx"
    owner: youtrack
  loop:
    - /opt/youtrack/home
    - /opt/youtrack/src
    - "{{youtrack_data_path}}"
    - /var/lib/youtrack/backups
    - /var/lib/youtrack/temp
    - /var/lib/youtrack/logs
  become: yes

- name: Add the user 'youtrack'
  user:
    name: youtrack
    shell: /bin/bash
    home: /opt/youtrack/home
  become: yes

- file:
    path: /var/log/youtrack
    state: directory
    mode: "u=rwX,g=rX,o=rX"
    owner: youtrack
    group: youtrack
  become: yes
  changed_when: false

- set_fact:
    youtrack_path_jar: "/opt/youtrack/src/youtrack-{{youtrack_version}}.jar"
    cacheable: true

- name: Download jar
  become: yes
  get_url:
    url: "{{youtrack_dstr_url}}"
    dest: "{{youtrack_path_jar}}"
    sha256sum: "{{youtrack_dstr_sha256sum}}"
    mode: 0640
    force: no
    owner: youtrack

- name: Configure for reversy proxy
  become: yes
  become_user: youtrack
  command: "/usr/bin/java -jar {{youtrack_path_jar}} configure --listen-port 8080  --base-url {{youtrack_url_scheme}}://{{youtrack_server_name}} -J-Djetbrains.youtrack.default.page={{youtrack_default_page}}"

- name: create systemd unit
  become: yes
  template:
    src: youtrack.service.j2
    dest: /etc/systemd/system/youtrack.service
    owner: root
    group: root
    mode: 0644
  notify: youtrack restart

- name: create nginx site
  become: yes
  template:
    src: youtrack.site.j2
    dest: /etc/nginx/sites/youtrack.site
    owner: root
    group: root
    mode: 0644
  notify: nginx restart

- systemd: 
    daemon_reload: yes
  become: yes

- systemd: 
    name: youtrack
    enabled: yes
    state: started 
  become: yes

- ufw:
    rule: allow
    port: 80
  become: yes
